### ISSUE TITLE
What version of rustfmt does codechain-miner use?

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain-miner#4]

**Comment by kakao-jun-e** [comment]
@kseo I have updated the version of rustfmt to equal the format of codechain. #5

**Comment by remagpie** [comment]
@kseo Sorry for the late response.
I guess it was `nightly-2018-05-07` version.
But I think it'd be better to keep sync with CodeChain main client.

**Comment by remagpie** [comment]
@redongjun Thanks for the PR. It's merged now.

**Comment by kseo** [comment]
Thanks
